[theme]

# Primary accent for interactive elements
primaryColor = 'white'

# Background color for the main content area
backgroundColor = 'gray'

# Color used for almost all text
textColor = 'black'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif" 
